import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Popping Perfectionism",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <link
                rel="icon"
                href="/icon?<generated>"
                type="image/<generated>"
                sizes="<generated>"
            />
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
            />
            <link rel="stylesheet" href="/globals.css" />
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Questrial:wght@100;200;300;400;500;600;700;800;900&display=swap"
            />

            <body className={inter.className}>{children}</body>
        </html>
    );
}
